# KNN K-cross validation bilan

In [1]:
import pandas as pd
df=pd.read_csv('student_depression_dataset(in).csv')

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27901 entries, 0 to 27900
Data columns (total 18 columns):
 #   Column                                 Non-Null Count  Dtype  
---  ------                                 --------------  -----  
 0   id                                     27816 non-null  float64
 1   Gender                                 27816 non-null  object 
 2   Age                                    27775 non-null  float64
 3   City                                   27728 non-null  object 
 4   Profession                             27775 non-null  object 
 5   Academic Pressure                      27775 non-null  float64
 6   Work Pressure                          27733 non-null  float64
 7   CGPA                                   27733 non-null  float64
 8   Study Satisfaction                     27733 non-null  float64
 9   Job Satisfaction                       27733 non-null  float64
 10  Sleep Duration                         27698 non-null  object 
 11  Di

In [3]:
df.head()

id  Gender   Age           City Profession  Academic Pressure  \
0   2.0    Male  33.0  Visakhapatnam    Student                5.0   
1   8.0  Female  24.0      Bangalore    Student                2.0   
2  26.0    Male  31.0       Srinagar    Student                3.0   
3  30.0  Female  28.0       Varanasi    Student                3.0   
4  32.0  Female  25.0         Jaipur    Student                4.0   

   Work Pressure  CGPA  Study Satisfaction  Job Satisfaction  \
0            0.0  8.97                 2.0               0.0   
1            0.0  5.90                 5.0               0.0   
2            0.0  7.03                 5.0               0.0   
3            0.0  5.59                 2.0               0.0   
4            0.0  8.13                 3.0               0.0   

        Sleep Duration Dietary Habits   Degree  \
0          '5-6 hours'        Healthy  B.Pharm   
1          '5-6 hours'       Moderate      BSc   
2  'Less than 5 hours'        Healthy       BA   
3          '7-8 hours'       Moderate      BCA   
4          '5-6 hours'       Moderate   M.Tech   

  Have you ever had suicidal thoughts ?  Work/Study Hours Financial Stress  \
0                                   Yes               3.0                1   
1                                    No               3.0                2   
2                                    No               9.0                1   
3                                   Yes               4.0                5   
4                                   Yes               1.0                1   

  Family History of Mental Illness  Depression  
0                               No         1.0  
1                              Yes         0.0  
2                              Yes         0.0  
3                              Yes         1.0  
4                               No         0.0

In [4]:
def tozala(df):
    for col in df.columns:
        if df[col].isnull().any():
            if df[col].dtype=='object':
                df[col].fillna(df[col].mode()[0],inplace=True)
            else:
                df[col].fillna(df[col].mean(),inplace=True)
    return df

In [5]:
tozala(df)

id  Gender   Age           City Profession  Academic Pressure  \
0           2.0    Male  33.0  Visakhapatnam    Student                5.0   
1           8.0  Female  24.0      Bangalore    Student                2.0   
2          26.0    Male  31.0       Srinagar    Student                3.0   
3          30.0  Female  28.0       Varanasi    Student                3.0   
4          32.0  Female  25.0         Jaipur    Student                4.0   
...         ...     ...   ...            ...        ...                ...   
27896  140685.0  Female  27.0          Surat    Student                5.0   
27897  140686.0    Male  27.0       Ludhiana    Student                2.0   
27898  140689.0    Male  31.0      Faridabad    Student                3.0   
27899  140690.0  Female  18.0       Ludhiana    Student                5.0   
27900  140699.0    Male  27.0          Patna    Student                4.0   

       Work Pressure  CGPA  Study Satisfaction  Job Satisfaction  \
0                0.0  8.97                 2.0               0.0   
1                0.0  5.90                 5.0               0.0   
2                0.0  7.03                 5.0               0.0   
3                0.0  5.59                 2.0               0.0   
4                0.0  8.13                 3.0               0.0   
...              ...   ...                 ...               ...   
27896            0.0  5.75                 5.0               0.0   
27897            0.0  9.40                 3.0               0.0   
27898            0.0  6.61                 4.0               0.0   
27899            0.0  6.88                 2.0               0.0   
27900            0.0  9.24                 1.0               0.0   

            Sleep Duration Dietary Habits      Degree  \
0              '5-6 hours'        Healthy     B.Pharm   
1              '5-6 hours'       Moderate         BSc   
2      'Less than 5 hours'        Healthy          BA   
3              '7-8 hours'       Moderate         BCA   
4              '5-6 hours'       Moderate      M.Tech   
...                    ...            ...         ...   
27896          '5-6 hours'      Unhealthy  'Class 12'   
27897  'Less than 5 hours'        Healthy         MSc   
27898          '5-6 hours'      Unhealthy          MD   
27899  'Less than 5 hours'        Healthy  'Class 12'   
27900  'Less than 5 hours'        Healthy         BCA   

      Have you ever had suicidal thoughts ?  Work/Study Hours  \
0                                       Yes               3.0   
1                                        No               3.0   
2                                        No               9.0   
3                                       Yes               4.0   
4                                       Yes               1.0   
...                                     ...               ...   
27896                                   Yes               7.0   
27897                                    No               0.0   
27898                                    No              12.0   
27899                                   Yes              10.0   
27900                                   Yes               2.0   

      Financial Stress Family History of Mental Illness  Depression  
0                    1                               No         1.0  
1                    2                              Yes         0.0  
2                    1                              Yes         0.0  
3                    5                              Yes         1.0  
4                    1                               No         0.0  
...                ...                              ...         ...  
27896                1                              Yes         0.0  
27897                3                              Yes         0.0  
27898                2                               No         0.0  
27899                5                               No         1.0  
27900                3 

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27901 entries, 0 to 27900
Data columns (total 18 columns):
 #   Column                                 Non-Null Count  Dtype  
---  ------                                 --------------  -----  
 0   id                                     27901 non-null  float64
 1   Gender                                 27901 non-null  object 
 2   Age                                    27901 non-null  float64
 3   City                                   27901 non-null  object 
 4   Profession                             27901 non-null  object 
 5   Academic Pressure                      27901 non-null  float64
 6   Work Pressure                          27901 non-null  float64
 7   CGPA                                   27901 non-null  float64
 8   Study Satisfaction                     27901 non-null  float64
 9   Job Satisfaction                       27901 non-null  float64
 10  Sleep Duration                         27901 non-null  object 
 11  Di

In [9]:
from sklearn.preprocessing import LabelEncoder, StandardScaler
encoder1=LabelEncoder()

In [13]:
def encod_qil(df):
    df = df.copy()

    for col in df.columns:
        if df[col].dtype == 'object':
            df[col] = encoder1.fit_transform(df[col])
    
    return df

In [14]:
df=encod_qil(df)

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27901 entries, 0 to 27900
Data columns (total 18 columns):
 #   Column                                 Non-Null Count  Dtype  
---  ------                                 --------------  -----  
 0   id                                     27901 non-null  float64
 1   Gender                                 27901 non-null  int32  
 2   Age                                    27901 non-null  float64
 3   City                                   27901 non-null  int32  
 4   Profession                             27901 non-null  int32  
 5   Academic Pressure                      27901 non-null  float64
 6   Work Pressure                          27901 non-null  float64
 7   CGPA                                   27901 non-null  float64
 8   Study Satisfaction                     27901 non-null  float64
 9   Job Satisfaction                       27901 non-null  float64
 10  Sleep Duration                         27901 non-null  int32  
 11  Di

In [17]:
df['Depression'] = df['Depression'].astype(int)

In [16]:
from sklearn.preprocessing import StandardScaler
scaling1=StandardScaler()

In [18]:
def scaling_qil(df):
    num_col=df.select_dtypes(include=['number']).columns.drop('Depression')
    df[num_col]=scaling1.fit_transform(df[num_col])
    return df

In [19]:
df=scaling_qil(df)

In [20]:
df.head()

id    Gender       Age      City  Profession  Academic Pressure  \
0 -1.733465  0.889088  1.466181  1.540949     0.02642           1.348108   
1 -1.733317 -1.124749 -0.372632 -1.434496     0.02642          -0.828514   
2 -1.732874  0.889088  1.057556  1.088164     0.02642          -0.102973   
3 -1.732775 -1.124749  0.444618  1.411582     0.02642          -0.102973   
4 -1.732726 -1.124749 -0.168320 -0.593610     0.02642           0.622567   

   Work Pressure      CGPA  Study Satisfaction  Job Satisfaction  \
0      -0.009836  0.896352           -0.695722         -0.015433   
1      -0.009836 -1.197983            1.515678         -0.015433   
2      -0.009836 -0.427104            1.515678         -0.015433   
3      -0.009836 -1.409463           -0.695722         -0.015433   
4      -0.009836  0.323309            0.041411         -0.015433   

   Sleep Duration  Dietary Habits    Degree  \
0       -1.429935       -1.188884 -0.588638   
1       -1.429935       -0.383625  0.252254   
2        0.457188       -1.188884 -0.348383   
3       -0.486373       -0.383625 -0.108128   
4       -1.429935       -0.383625  0.973019   

   Have you ever had suicidal thoughts ?  Work/Study Hours  Financial Stress  \
0                               0.757638         -1.124968         -1.493855   
1                              -1.319891         -1.124968         -0.799639   
2                              -1.319891          0.498247         -1.493855   
3                               0.757638         -0.854432          1.283010   
4                               0.757638         -1.666040         -1.493855   

   Family History of Mental Illness  Depression  
0                         -0.961978           1  
1                          1.039525           0  
2                          1.039525           0  
3                          1.039525           1  
4                         -0.961978           0

In [21]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [22]:
x=df.drop('Depression',axis=1)

In [24]:
y=df['Depression']

In [25]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [26]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
from sklearn.neighbors import KNeighborsClassifier   # Classification uchun
from sklearn.neighbors import KNeighborsRegressor    # Regression uchun

In [27]:
model1=KNeighborsClassifier(n_neighbors=5)

In [28]:
model1

KNeighborsClassifier()

In [30]:
model1.fit(x_train,y_train)

KNeighborsClassifier()

In [31]:
y_pred=model1.predict(x_test)

In [32]:
y_pred

array([0, 0, 0, ..., 0, 0, 1])

In [33]:
score1=accuracy_score(y_test,y_pred)

In [35]:
print(f"KNN aniqligi:{score1*100}%ga teng")

KNN aniqligi:80.46944991936928%ga teng


In [36]:
# K- cross validation

from sklearn.model_selection import cross_val_score,KFold

In [39]:
kf=KFold(n_splits=5,shuffle=True,random_state=42)
scores1=cross_val_score(model1,x,y,cv=kf,scoring='accuracy')
print(scores1)

[0.8046945  0.81827957 0.82132616 0.81505376 0.81756272]


In [40]:
import numpy as np

In [ ]:
print(np.mean(scores1).round(2))
# .round(2) -   bu kodda natijada nechta sonni kormoqchi bolsak qavsni ichiga shu sonni yozishimiz mumkin

0.82


In [47]:
print(np.mean(scores1))

0.8153833442831828


In [48]:
np.std(scores1)

0.005706399359533396

# SVM K-cross validation bilan

In [75]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [76]:
x=df.drop('Depression',axis=1)

In [77]:
y=df['Depression']

In [78]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [55]:
from sklearn.svm import SVC

In [79]:
from sklearn.svm import SVR

In [56]:
model2=SVC(kernel='linear',random_state=42)

In [80]:
model3=SVC(kernel='rbf')

In [57]:
model2

SVC(kernel='linear', random_state=42)

In [81]:
model3

SVC()

In [83]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [61]:
model2.fit(x_train,y_train)

SVC(kernel='linear', random_state=42)

In [84]:
model3.fit(x_train,y_train)

SVC()

In [62]:
model2

SVC(kernel='linear', random_state=42)

In [85]:
model3

SVC()

In [63]:
y_pred=model2.predict(x_test)

In [86]:
y_pred2=model3.predict(x_test)

In [64]:
y_pred

array([0, 0, 0, ..., 1, 0, 1])

In [87]:
y_pred2

array([0, 0, 0, ..., 1, 0, 1])

In [65]:
score2=accuracy_score(y_test,y_pred)

In [88]:
score3=accuracy_score(y_test,y_pred)

In [ ]:
# Classification linear
print(f"SVM aniqligi:{score2*100}%ga teng")

SVM aniqligi:83.26464791256048%ga teng


In [ ]:
# Regression rbf
print(f"SVM rbf aniqligi:{score3 *100}%ga teng")

SVM rbf aniqligi:83.26464791256048%ga teng


In [67]:
# K-cross validation

from sklearn.model_selection import cross_val_score,KFold

In [ ]:
# Classification linear
kf2=KFold(n_splits=5,shuffle=True,random_state=42)
scores2=cross_val_score(model2,x,y,cv=kf,scoring='accuracy')
print(scores2)

[0.83264648 0.84354839 0.84659498 0.83584229 0.84193548]


In [ ]:
# Regression rbf
kf3=KFold(n_splits=5,shuffle=True,random_state=42)
scores3=cross_val_score(model3,x,y,cv=kf,scoring='accuracy')
print(scores3)

[0.83300484 0.84301075 0.85125448 0.83870968 0.84713262]


In [70]:
import numpy as np

In [ ]:
print(np.mean(scores2).round(2))   # Classsification 'linear' uchun

0.84


In [ ]:
print(np.mean(scores3).round(2))    # Regression 'rbf' uchun

0.84


In [ ]:
print(np.mean(scores2))      # Classsification 'linear' uchun

0.8401135252158018


In [ ]:
print(np.mean(scores3))       # Regression 'rbf' uchun

0.8426224729448804


In [ ]:
np.std(scores2)          # Classsification 'linear' uchun

0.005121079705650436

In [ ]:
np.std(scores3)         # Regression 'rbf' uchun

0.006368870864874065