# Logistic Regression

In [22]:
import pandas as pd
df=pd.read_csv('diabetes_prediction_dataset.csv')

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 9 columns):
 #   Column               Non-Null Count   Dtype  
---  ------               --------------   -----  
 0   gender               100000 non-null  object 
 1   age                  100000 non-null  float64
 2   hypertension         100000 non-null  int64  
 3   heart_disease        100000 non-null  int64  
 4   smoking_history      100000 non-null  object 
 5   bmi                  100000 non-null  float64
 6   HbA1c_level          100000 non-null  float64
 7   blood_glucose_level  100000 non-null  int64  
 8   diabetes             100000 non-null  int64  
dtypes: float64(3), int64(4), object(2)
memory usage: 6.9+ MB


In [24]:
# missing valuelar yoq,lekin missing value kodini yozib ketamiz
def tozala(df):
    for col in df.columns:
        if df[col].isnull().any():
            if df[col].dtype=='object':
                df[col].fillna(df[col].mode()[0],inplace=True)
            else:
                df[col].fillna(df[col].mean(),inplace=True)
                

In [25]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()

# encoding
def encod_qil(df):
    for col in df.columns:
        if df[col].dtype=='object':
            df[col]=encoder.fit_transform(df[col])
    return df

In [26]:
df=encod_qil(df)

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 9 columns):
 #   Column               Non-Null Count   Dtype  
---  ------               --------------   -----  
 0   gender               100000 non-null  int32  
 1   age                  100000 non-null  float64
 2   hypertension         100000 non-null  int64  
 3   heart_disease        100000 non-null  int64  
 4   smoking_history      100000 non-null  int32  
 5   bmi                  100000 non-null  float64
 6   HbA1c_level          100000 non-null  float64
 7   blood_glucose_level  100000 non-null  int64  
 8   diabetes             100000 non-null  int64  
dtypes: float64(3), int32(2), int64(4)
memory usage: 6.1 MB


In [37]:
# Scaling
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

def scaling_qil(df):
    num_col=df.select_dtypes(include=['int32','float64']).columns
    if 'diabetes' in num_col:
        num_col = num_col.drop('diabetes')  # Faqat bor bo‘lsa tushiramiz
    df[num_col]=scaler.fit_transform(df[num_col])
    return df

In [38]:
df=scaling_qil(df)

In [39]:
df.head()

gender       age  hypertension  heart_disease  smoking_history       bmi  \
0 -0.841047  1.692704             0              1         0.963327 -0.321056   
1 -0.841047  0.538006             0              0        -1.153468 -0.000116   
2  1.187234 -0.616691             0              0         0.963327 -0.000116   
3 -0.841047 -0.261399             0              0        -0.624269 -0.583232   
4  1.187234  1.515058             1              1        -0.624269 -1.081970   

   HbA1c_level  blood_glucose_level  diabetes  
0     1.001706                  140         0  
1     1.001706                   80         0  
2     0.161108                  158         0  
3    -0.492690                  155         0  
4    -0.679490                  155         0

# Training

In [105]:
x=df.drop('diabetes',axis=1)

In [106]:
y=df['diabetes']

In [69]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [107]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [44]:
lc_model=LogisticRegression()

In [45]:
lc_model

LogisticRegression()

In [46]:
lc_model.fit(x_train,y_train)

LogisticRegression()

In [47]:
y_pred=lc_model.predict(x_test)

In [48]:
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [49]:
from sklearn.metrics import accuracy_score

In [50]:
acc1=accuracy_score(y_test,y_pred)

In [51]:
print(f'LogisticRegression aniqligi:{acc1*100}%ga teng')

#2. f'...' → bu f-string (formatlangan string)
# f harfi formatlash degani: matn ichida o‘zgaruvchilarni bevosita joylashtirish imkonini beradi.

#F-string ichida {} ichiga o‘zgaruvchi nomini yozsangiz, Python u o‘zgaruvchining qiymatini joylashtiradi.

# 3. 'LogisticRegression aniqligi:{acc1*100}%ga teng'
#Bu yerda matn va o‘zgaruvchi aralashtirilgan:

#'LogisticRegression aniqligi: → bu oddiy matn.

#{acc1*100} → bu f-string ichidagi hisoblash.

#acc1 — bu sizning oldin hisoblangan aniqlik (accuracy) qiymatingiz.

#acc1*100 — accuracy ni foizga aylantiryapti (masalan: 0.83 → 83.0).

#'%ga teng' — bu oddiy matn bo‘lib, foiz degan belgi ko‘rinadi.

# f'...'	Formatlangan matn
# {acc1*100}	acc1 qiymatini 100 ga ko‘paytiradi

LogisticRegression aniqligi:95.89%ga teng


# LogisticRegression K-cross validation bilan

In [52]:
from sklearn.model_selection import cross_val_score,KFold

In [54]:
kf1=KFold(n_splits=5,shuffle=True,random_state=42)
scores1=cross_val_score(lc_model,x,y,cv=kf1,scoring='accuracy')
print(scores1)

C:\Users\xolmu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\xolmu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stab

[0.9589  0.96055 0.96045 0.96125 0.9605 ]


C:\Users\xolmu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [55]:
print(scores1)

[0.9589  0.96055 0.96045 0.96125 0.9605 ]


In [56]:
import numpy as np

In [58]:
print(np.mean(scores1).round(4))

0.9603


In [59]:
np.std(scores1)

0.0007723988606931243

# Decision Tree

In [64]:
# Training
from sklearn.tree import DecisionTreeClassifier


In [71]:
dt_model=DecisionTreeClassifier()

In [72]:
dt_model.fit(x_train,y_train)

DecisionTreeClassifier()

In [73]:
y_pred=dt_model.predict(x_test)

In [74]:
y_pred

array([0, 0, 0, ..., 0, 0, 1], dtype=int64)

In [75]:
from sklearn.metrics import accuracy_score

In [78]:
acc2=accuracy_score(y_test,y_pred)

In [79]:
acc2

0.95215

In [80]:
print(f'DecisionTree aniqligi:{acc2*100}%ga teng')

DecisionTree aniqligi:95.215%ga teng


# DecisionTree K-cross validation bilan

In [82]:
kf2=KFold(n_splits=5,shuffle=True,random_state=42)
scores2=cross_val_score(dt_model,x,y,cv=kf2,scoring='accuracy')
print(scores2)

[0.9516  0.9525  0.9503  0.95325 0.95015]


In [83]:
print(np.mean(scores2).round(4))

0.9516


In [84]:
np.std(scores2)

0.0012097107092193522

# RandomForest

In [87]:
from sklearn.ensemble import RandomForestClassifier

In [89]:
rf_model=RandomForestClassifier()

In [90]:
rf_model.fit(x_train,y_train)

RandomForestClassifier()

In [91]:
y_pred=rf_model.predict(x_test)

In [92]:
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [93]:
acc3=accuracy_score(y_test,y_pred)

In [94]:
print(f'RandomForestClassifier aniqligi:{acc3*100}%ga teng')

RandomForestClassifier aniqligi:97.02499999999999%ga teng


# RandomForest K-cross validation bilan

In [96]:
kf3=KFold(n_splits=5,shuffle=True,random_state=42)
scores3=cross_val_score(rf_model,x,y,cv=kf3,scoring='accuracy')
print(scores3)

[0.9699  0.9701  0.96905 0.9714  0.969  ]


In [99]:
print(np.mean(scores3).round(4))

0.9699


In [100]:
np.std(scores3)

0.0008742997197758001

# KNN

In [108]:
from sklearn.neighbors import KNeighborsClassifier
knn_model=KNeighborsClassifier()

In [109]:
knn_model

KNeighborsClassifier()

In [110]:
knn_model.fit(x_train,y_train)

KNeighborsClassifier()

In [111]:
y_pred=knn_model.predict(x_test)

In [112]:
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [113]:
acc4=accuracy_score(y_test,y_pred)

In [114]:
print(f'KNN aniqligi:{acc4*100}ga teng')

KNN aniqligi:96.06ga teng


# KNN K-cross validation bilan

In [115]:
kf4=KFold(n_splits=5,shuffle=True,random_state=42)
scores4=cross_val_score(knn_model,x,y,cv=kf4,scoring='accuracy')
print(scores4)

[0.9605  0.9616  0.96135 0.96285 0.96135]


In [117]:
print(np.mean(scores4).round(4))

0.9615


In [118]:
np.std(scores4)

0.0007580237463298743

# Tabulate

In [119]:
from tabulate import tabulate

In [120]:
df = [
    {
        "Modelning chiqgan natijalari": "LogisticRegression", 
        "accuracy_score": "6chi-95.89%", 
        "K-cross validation bilan": "5chi-0.9603%"
    },

    {
        "Modelning chiqgan natijalari": "DecisionTree", 
        "accuracy_score": "7chi-95.215%",
        "K-cross validation bilan": "8chi-0.9516%"
    },

    {"Modelning chiqgan natijalari": "RandomForest", 
        "accuracy_score": "1chi-97.02%",
        "K-cross validation bilan": "2chi-0.9699%"

    },

    {"Modelning chiqgan natijalari": "KNN", 
        "accuracy_score": "4chi-96.06%",
        "K-cross validation bilan": "3chi-0.9615%"}
]

print(tabulate(df, headers="keys", tablefmt="grid"))

+--------------------------------+------------------+----------------------------+
| Modelning chiqgan natijalari   | accuracy_score   | K-cross validation bilan   |
+================================+==================+============================+
| LogisticRegression             | 6chi-95.89%      | 5chi-0.9603%               |
+--------------------------------+------------------+----------------------------+
| DecisionTree                   | 7chi-95.215%     | 8chi-0.9516%               |
+--------------------------------+------------------+----------------------------+
| RandomForest                   | 1chi-97.02%      | 2chi-0.9699%               |
+--------------------------------+------------------+----------------------------+
| KNN                            | 4chi-96.06%      | 3chi-0.9615%               |
+--------------------------------+------------------+----------------------------+
