# Decision Tree

In [51]:
import pandas as pd
from sklearn.model_selection import train_test_split,KFold,cross_val_score
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler


In [2]:
df=pd.read_csv('tuberculosis_xray_dataset 4.csv')

In [3]:
df.head()

Patient_ID Age  Gender Chest_Pain  Cough_Severity  Breathlessness Fatigue  \
0  PID000001  69    Male        Yes             1.0             2.0       3   
1  PID000002  32  Female        Yes             3.0             0.0       9   
2  PID000003  89    Male         No             7.0             0.0       3   
3  PID000004  78  Female        Yes             2.0             0.0       6   
4  PID000005  38    Male         No             7.0             2.0       5   

  Weight_Loss     Fever Night_Sweats Sputum_Production Blood_in_Sputum  \
0        2.37  Moderate          Yes            Medium             Yes   
1        6.09  Moderate           No            Medium              No   
2        2.86      Mild          Yes            Medium              No   
3        4.57  Moderate           No              High             Yes   
4       13.86      High          Yes               Low              No   

  Smoking_History Previous_TB_History         Class  
0          Former                 Yes        Normal  
1         Current                 Yes        Normal  
2         Current                  No  Tuberculosis  
3           Never                 Yes  Tuberculosis  
4           Never                 Yes  Tuberculosis

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19986 entries, 0 to 19985
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Patient_ID           19986 non-null  object 
 1   Age                  19986 non-null  object 
 2   Gender               19985 non-null  object 
 3   Chest_Pain           19986 non-null  object 
 4   Cough_Severity       19985 non-null  float64
 5   Breathlessness       19986 non-null  float64
 6   Fatigue              19986 non-null  object 
 7   Weight_Loss          19986 non-null  object 
 8   Fever                19986 non-null  object 
 9   Night_Sweats         19986 non-null  object 
 10  Sputum_Production    19986 non-null  object 
 11  Blood_in_Sputum      19986 non-null  object 
 12  Smoking_History      19985 non-null  object 
 13  Previous_TB_History  19985 non-null  object 
 14  Class                19884 non-null  object 
dtypes: float64(2), object(13)
memory usa

In [ ]:
df['Age']=df['Age'].map({          # Mapping Usuli
    'Age':1,
    'no Age':0
})

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19986 entries, 0 to 19985
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Patient_ID           19986 non-null  object 
 1   Age                  0 non-null      float64
 2   Gender               19985 non-null  object 
 3   Chest_Pain           19986 non-null  object 
 4   Cough_Severity       19985 non-null  float64
 5   Breathlessness       19986 non-null  float64
 6   Fatigue              19986 non-null  object 
 7   Weight_Loss          19986 non-null  object 
 8   Fever                19986 non-null  object 
 9   Night_Sweats         19986 non-null  object 
 10  Sputum_Production    19986 non-null  object 
 11  Blood_in_Sputum      19986 non-null  object 
 12  Smoking_History      19985 non-null  object 
 13  Previous_TB_History  19985 non-null  object 
 14  Class                19884 non-null  object 
dtypes: float64(3), object(12)
memory usa

In [7]:
df.head()

Patient_ID  Age  Gender Chest_Pain  Cough_Severity  Breathlessness Fatigue  \
0  PID000001  NaN    Male        Yes             1.0             2.0       3   
1  PID000002  NaN  Female        Yes             3.0             0.0       9   
2  PID000003  NaN    Male         No             7.0             0.0       3   
3  PID000004  NaN  Female        Yes             2.0             0.0       6   
4  PID000005  NaN    Male         No             7.0             2.0       5   

  Weight_Loss     Fever Night_Sweats Sputum_Production Blood_in_Sputum  \
0        2.37  Moderate          Yes            Medium             Yes   
1        6.09  Moderate           No            Medium              No   
2        2.86      Mild          Yes            Medium              No   
3        4.57  Moderate           No              High             Yes   
4       13.86      High          Yes               Low              No   

  Smoking_History Previous_TB_History         Class  
0          Former                 Yes        Normal  
1         Current                 Yes        Normal  
2         Current                  No  Tuberculosis  
3           Never                 Yes  Tuberculosis  
4           Never                 Yes  Tuberculosis

In [5]:
from datacleaner import autoclean

In [6]:
df=autoclean(df)

C:\Users\xolmu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\datacleaner\datacleaner.py:77: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  input_dataframe[column].fillna(input_dataframe[column].median(), inplace=True)
C:\Users\xolmu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\datacleaner\datacleaner.py:77: FutureWarning: A value is trying to be set on a copy of a DataFrame

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19986 entries, 0 to 19985
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Patient_ID           19986 non-null  int64  
 1   Age                  19986 non-null  int64  
 2   Gender               19986 non-null  int64  
 3   Chest_Pain           19986 non-null  int64  
 4   Cough_Severity       19986 non-null  float64
 5   Breathlessness       19986 non-null  float64
 6   Fatigue              19986 non-null  int64  
 7   Weight_Loss          19986 non-null  int64  
 8   Fever                19986 non-null  int64  
 9   Night_Sweats         19986 non-null  int64  
 10  Sputum_Production    19986 non-null  int64  
 11  Blood_in_Sputum      19986 non-null  int64  
 12  Smoking_History      19986 non-null  int64  
 13  Previous_TB_History  19986 non-null  int64  
 14  Class                19986 non-null  int64  
dtypes: float64(2), int64(13)
memory usag

In [8]:
df.head()

Patient_ID  Age  Gender  Chest_Pain  Cough_Severity  Breathlessness  \
0           7   51       2          11             1.0             2.0   
1           8   14       1          11             3.0             0.0   
2           9   71       2          10             7.0             0.0   
3          10   60       1          11             2.0             0.0   
4          11   20       2          10             7.0             2.0   

   Fatigue  Weight_Loss  Fever  Night_Sweats  Sputum_Production  \
0       25          738      3             4                  2   
1       41         1110      3             3                  2   
2       25          787      2             4                  2   
3       30          958      3             3                  0   
4       29          586      0             4                  1   

   Blood_in_Sputum  Smoking_History  Previous_TB_History  Class  
0                5                1                    3      0  
1                3                0                    3      0  
2                3                0                    0      1  
3                5                2                    3      1  
4                3                2                    3      1

# Decision Tree

In [36]:
x=df.drop('Patient_ID',axis=1)

In [37]:
x

Age    Gender  Chest_Pain  Cough_Severity  Breathlessness  \
0      0.746355  0.972224    0.957881       -1.217984       -0.004683   
1     -1.033423 -1.013152    0.957881       -0.519747       -1.410633   
2      1.708398  0.972224   -0.897898        0.876727       -1.410633   
3      1.179275 -1.013152    0.957881       -0.868866       -1.410633   
4     -0.744810  0.972224   -0.897898        0.876727       -0.004683   
...         ...       ...         ...             ...             ...   
19981 -0.023278 -1.013152   -0.897898       -0.519747        1.401267   
19982 -1.273934  0.972224   -0.897898       -1.217984       -0.707658   
19983 -1.466342 -1.013152   -0.897898        1.225845       -0.004683   
19984 -1.418240  0.972224   -0.897898        1.574964        1.401267   
19985 -0.263789  0.972224   -0.897898       -0.170629        1.401267   

        Fatigue  Weight_Loss     Fever  Night_Sweats  Sputum_Production  \
0      0.018107    -0.028279  1.050259      0.985088           1.189303   
1      1.328071     0.823491  1.050259     -0.950799           1.189303   
2      0.018107     0.083916  0.251383      0.985088           1.189303   
3      0.427470     0.475456  1.050259     -0.950799          -1.223345   
4      0.345598    -0.376314 -1.346370      0.985088          -0.017021   
...         ...          ...       ...           ...                ...   
19981  0.427470    -0.866311  1.050259      0.985088           1.189303   
19982 -1.537476     0.727323  1.050259      0.985088          -0.017021   
19983  0.918707     0.324335 -1.346370      0.985088          -0.017021   
19984  0.427470     1.437131  1.050259      0.985088           1.189303   
19985  0.263725     0.537278 -1.346370     -0.950799          -1.223345   

       Blood_in_Sputum  Smoking_History  Previous_TB_History     Class  
0             1.003891        -0.014257             0.996108 -0.646412  
1            -0.967881        -1.221673             0.996108 -0.646412  
2            -0.967881        -1.221673            -1.007672  1.547000  
3             1.003891         1.193158             0.996108  1.547000  
4            -0.967881         1.193158             0.996108  1.547000  
...                ...              ...                  ...       ...  
19981        -0.967881         1.193158             0.996108 -0.646412  
19982         1.003891        -1.221673             0.996108  1.547000  
19983         1.003891         1.193158            -1.007672 -0.646412  
19984         1.003891         1.193158             0.996108 -0.646412  
19985        -0.967881         1.193158             0.996108 -0.646412  

[19986 rows x 14 columns]

In [38]:
y=df['Patient_ID']

In [39]:
y

0       -1.730404
1       -1.730231
2       -1.730058
3       -1.729884
4       -1.729711
           ...   
19981    1.731271
19982    1.731444
19983    1.731618
19984    1.731791
19985    1.731964
Name: Patient_ID, Length: 19986, dtype: float64

In [40]:
x_train,x_temp,y_train,y_temp=train_test_split(x,y,test_size=0.2,random_state=42)
x_test,x_val,y_test,y_val=train_test_split(x_temp,y_temp,test_size=0.5,random_state=42)

In [41]:
x_train.shape,x_test.shape,x_val.shape

((15988, 14), (1999, 14), (1999, 14))

In [42]:
y_train.shape,y_test.shape,y_val.shape

((15988,), (1999,), (1999,))

In [59]:
dt_model=DecisionTreeRegressor(random_state=42)

In [60]:
dt_model

DecisionTreeRegressor(random_state=42)

In [61]:
dt_model.fit(x_train,y_train)

DecisionTreeRegressor(random_state=42)

In [62]:
dt_model

DecisionTreeRegressor(random_state=42)

In [40]:
y_pred=dt_model.predict(x_val)

In [41]:
y_pred

array([ 1221., 11546.,  1969., ...,  8431., 17811., 18073.], shape=(1999,))

In [63]:
mse=mean_squared_error(y_val,y_pred)
r2=r2_score(y_val,y_pred)

In [64]:
print('DT model')
print('Mean Squared Error:',mse)
print('R2 Score:',r2)

DT model
Mean Squared Error: 0.9857153913448506
R2 Score: -0.0029359189738478175


In [ ]:
# 1chi holat.bunda Random state yoq,hali scaling bolmagan

#DT model
#Mean Squared Error: 67410436.36168084
#R2 Score: -1.0605272303569224


# 2chi holat.bunda ham Random State yoq,hali scaling bolmagan
#DT model
#Mean Squared Error: 65925647.02701351
#R2 Score: -1.0151418416759985

# random state bor bolganda chiqgan qiymat,hali scaling bolmagan
#DT model
#Mean Squared Error: 67362619.29414707
#R2 Score: -1.0590656114289496


# Linear Regression

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19986 entries, 0 to 19985
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Patient_ID           19986 non-null  int64  
 1   Age                  19986 non-null  int64  
 2   Gender               19986 non-null  int64  
 3   Chest_Pain           19986 non-null  int64  
 4   Cough_Severity       19986 non-null  float64
 5   Breathlessness       19986 non-null  float64
 6   Fatigue              19986 non-null  int64  
 7   Weight_Loss          19986 non-null  int64  
 8   Fever                19986 non-null  int64  
 9   Night_Sweats         19986 non-null  int64  
 10  Sputum_Production    19986 non-null  int64  
 11  Blood_in_Sputum      19986 non-null  int64  
 12  Smoking_History      19986 non-null  int64  
 13  Previous_TB_History  19986 non-null  int64  
 14  Class                19986 non-null  int64  
dtypes: float64(2), int64(13)
memory usag

In [31]:
num_col=df.select_dtypes(include='number').columns

In [32]:
num_col

Index(['Patient_ID', 'Age', 'Gender', 'Chest_Pain', 'Cough_Severity',
       'Breathlessness', 'Fatigue', 'Weight_Loss', 'Fever', 'Night_Sweats',
       'Sputum_Production', 'Blood_in_Sputum', 'Smoking_History',
       'Previous_TB_History', 'Class'],
      dtype='object')

In [ ]:
scaler=StandardScaler()                                     # Scaling boldi
df[num_col]=scaler.fit_transform(df[num_col])

In [35]:
df.head()

Patient_ID       Age    Gender  Chest_Pain  Cough_Severity  Breathlessness  \
0   -1.730404  0.746355  0.972224    0.957881       -1.217984       -0.004683   
1   -1.730231 -1.033423 -1.013152    0.957881       -0.519747       -1.410633   
2   -1.730058  1.708398  0.972224   -0.897898        0.876727       -1.410633   
3   -1.729884  1.179275 -1.013152    0.957881       -0.868866       -1.410633   
4   -1.729711 -0.744810  0.972224   -0.897898        0.876727       -0.004683   

    Fatigue  Weight_Loss     Fever  Night_Sweats  Sputum_Production  \
0  0.018107    -0.028279  1.050259      0.985088           1.189303   
1  1.328071     0.823491  1.050259     -0.950799           1.189303   
2  0.018107     0.083916  0.251383      0.985088           1.189303   
3  0.427470     0.475456  1.050259     -0.950799          -1.223345   
4  0.345598    -0.376314 -1.346370      0.985088          -0.017021   

   Blood_in_Sputum  Smoking_History  Previous_TB_History     Class  
0         1.003891        -0.014257             0.996108 -0.646412  
1        -0.967881        -1.221673             0.996108 -0.646412  
2        -0.967881        -1.221673            -1.007672  1.547000  
3         1.003891         1.193158             0.996108  1.547000  
4        -0.967881         1.193158             0.996108  1.547000

In [44]:
lr=LinearRegression()

In [45]:
lr

LinearRegression()

In [46]:
lr.fit(x_train,y_train)

LinearRegression()

In [47]:
lr

LinearRegression()

In [48]:
y_pred=lr.predict(x_val)

In [49]:
y_pred

array([ 0.02157342, -0.01054412, -0.01087802, ..., -0.03850331,
       -0.03135191,  0.03497679], shape=(1999,))

In [50]:
mse=mean_squared_error(y_val,y_pred)
r2=r2_score(y_val,y_pred)
print('Linear Regression:')
print('mse',mse)
print('r2',r2)

Linear Regression:
mse 0.9857153913448506
r2 -0.0029359189738478175


In [ ]:
# Linear Regression:                hozirgi holati,hali scaling bolmagan
# mse 32811188.779640354
# r2 -0.0029359189738478175


#DT model         random state bilan oldingi holati,hali scaling bolmagan
#Mean Squared Error: 67362619.29414707
#R2 Score: -1.0590656114289496


# Bu scaling bolgandagi qiymatlar
#Linear Regression:
#mse 0.9857153913448506
#r2 -0.0029359189738478175

# Cross Validation

In [52]:
kf=KFold(n_splits=5,shuffle=True,random_state=42)

In [53]:
kf

KFold(n_splits=5, random_state=42, shuffle=True)

In [54]:
scores=cross_val_score(lr,x_train,y_train,cv=kf,scoring='r2')

In [56]:
scores

array([-0.00051652, -0.00056333,  0.00043752, -0.00068186, -0.00199938])

In [57]:
scores.mean()

np.float64(-0.0006647122761767488)

In [58]:
scores.std()

np.float64(0.0007783035343094939)

In [65]:
# dt      decision tree bilan
scores=cross_val_score(dt_model,x_train,y_train,cv=kf,scoring='r2')


In [66]:
scores

array([-0.99721023, -1.06412798, -1.10861709, -1.00238807, -1.0304916 ])

In [67]:
scores.mean()

np.float64(-1.0405669937528237)

In [68]:
scores.std()

np.float64(0.04153284951791295)

In [69]:
y_pred

array([ 0.02157342, -0.01054412, -0.01087802, ..., -0.03850331,
       -0.03135191,  0.03497679], shape=(1999,))

In [70]:
len(y_pred)

1999

In [72]:
len(y_val)

1999

In [73]:
y_val

17221    1.252890
8596    -0.242050
15135    0.891331
8836    -0.200452
8132    -0.322474
           ...   
9029    -0.167000
2041    -1.378205
13115    0.541212
14266    0.740710
1006    -1.557598
Name: Patient_ID, Length: 1999, dtype: float64

In [74]:
y_pred

array([ 0.02157342, -0.01054412, -0.01087802, ..., -0.03850331,
       -0.03135191,  0.03497679], shape=(1999,))

# Metrics

In [76]:
from sklearn.metrics import mean_squared_error, r2_score

In [77]:
y_actual=[3,5,7,9,11]
y_pred=[2.8,5.5,6.7,8.9,10.5]
mse=mean_squared_error(y_actual,y_pred)
print(mse)

0.12799999999999997


In [78]:
r2=r2_score(y_actual,y_pred)
print(r2)

0.984
